version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app:cached
      - /app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      NODE_ENV: development
    command: pnpm dev --hostname 0.0.0.0
