export async function GET() {
  const courses = [
    {
      id: 1,
      title: "Advanced JavaScript & ES6+",
      instructor: "Sarah Johnson",
      progress: 65,
      students: 134,
      description: "Master modern JavaScript with ES6+ features and async patterns.",
      status: "in_progress",
      completedLessons: 13,
      totalLessons: 20,
      nextLesson: "Async/Await Patterns",
      estimatedTime: "45 mins",
      image: "/javascript-course.jpg",
    },
    {
      id: 2,
      title: "Web Development Fundamentals",
      instructor: "Mike Chen",
      progress: 48,
      students: 98,
      description: "Complete guide to HTML, CSS, JavaScript, and responsive design.",
      status: "in_progress",
      completedLessons: 9,
      totalLessons: 19,
      nextLesson: "CSS Grid & Flexbox",
      estimatedTime: "50 mins",
      image: "/web-development-course.jpg",
    },
    {
      id: 3,
      title: "React Mastery",
      instructor: "Emily Davis",
      progress: 82,
      students: 210,
      description: "Advanced React patterns, state management, and performance.",
      status: "in_progress",
      completedLessons: 16,
      totalLessons: 20,
      nextLesson: "Performance Optimization",
      estimatedTime: "55 mins",
      image: "/react-course.jpg",
    },
    {
      id: 4,
      title: "Modern History",
      instructor: "Michael Brown",
      progress: 100,
      students: 156,
      description: "Study of 20th and 21st century history.",
      status: "completed",
      completedLessons: 24,
      totalLessons: 24,
      nextLesson: "",
      estimatedTime: "",
      image: "/history-course.jpg",
    },
    {
      id: 5,
      title: "Literature & Composition",
      instructor: "James Miller",
      progress: 0,
      students: 75,
      description: "Contemporary literature analysis and writing.",
      status: "not_started",
      completedLessons: 0,
      totalLessons: 18,
      nextLesson: "Introduction",
      estimatedTime: "30 mins",
      image: "/literature-course.jpg",
    },
  ]

  return Response.json({ courses })
}
